<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class CategoriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = [
            [
                'name' => 'Cinematic Portrait',
                'slug' => 'پرتره سینمایی',
                'description' => 'Stylish, professionally composed character portraits with dramatic lighting and atmosphere',
                'color_hex' => '#3B82F6',
                'parent_id' => null,
                'sort_order' => 1,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Character Cosplay',
                'slug' => 'کازمپلی شخصیت',
                'description' => 'Realistic portrayals of fictional characters from anime, games, and media',
                'color_hex' => '#EF4444',
                'parent_id' => null,
                'sort_order' => 2,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Absurd Humor',
                'slug' => 'طنن ابسورد',
                'description' => 'Whimsical and humorous scenarios featuring unexpected character combinations and situations',
                'color_hex' => '#F59E0B',
                'parent_id' => null,
                'sort_order' => 3,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Anime',
                'slug' => 'انیمه',
                'description' => 'Artwork created in various anime and manga styles from different eras',
                'color_hex' => '#EC4899',
                'parent_id' => null,
                'sort_order' => 4,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Crossover Mashup',
                'slug' => 'ادغام فرنچایز',
                'description' => 'Creative combinations of characters and elements from different franchises',
                'color_hex' => '#8B5CF6',
                'parent_id' => null,
                'sort_order' => 5,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Character in Real Life',
                'slug' => 'شخصیت در زندگی واقعی',
                'description' => 'Fictional characters placed in realistic, everyday situations and environments',
                'color_hex' => '#06B6D4',
                'parent_id' => null,
                'sort_order' => 6,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Cute Selfie',
                'slug' => 'سلفی بامزه',
                'description' => 'Charming self-portrait style images with playful and endearing qualities',
                'color_hex' => '#F97316',
                'parent_id' => null,
                'sort_order' => 7,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Architectural Concept',
                'slug' => 'مفهوم معماری',
                'description' => 'Imaginative building designs and urban landscape concepts',
                'color_hex' => '#64748B',
                'parent_id' => null,
                'sort_order' => 8,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Political Portrait',
                'slug' => 'پرتره سیاسی',
                'description' => 'Satirical or serious depictions of political figures and scenarios',
                'color_hex' => '#475569',
                'parent_id' => null,
                'sort_order' => 9,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Album Art',
                'slug' => 'طرح آلبوم',
                'description' => 'Artwork designed for music albums and promotional materials',
                'color_hex' => '#10B981',
                'parent_id' => null,
                'sort_order' => 10,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Minimalist Photography',
                'slug' => 'عکاسی مینیمال',
                'description' => 'Clean, simple photographic compositions with emphasis on negative space',
                'color_hex' => '#6B7280',
                'parent_id' => null,
                'sort_order' => 11,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Sci-Fi Art',
                'slug' => 'هنر علمی تخیلی',
                'description' => 'Futuristic and speculative fiction artwork with technological themes',
                'color_hex' => '#6366F1',
                'parent_id' => null,
                'sort_order' => 12,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Animal Portrait',
                'slug' => 'پرتره حیوانات',
                'description' => 'Artistic depictions of animals in various styles and settings',
                'color_hex' => '#84CC16',
                'parent_id' => null,
                'sort_order' => 13,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Movie Poster',
                'slug' => 'پوستر فیلم',
                'description' => 'Promotional artwork designed in the style of movie posters',
                'color_hex' => '#DC2626',
                'parent_id' => null,
                'sort_order' => 14,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Artistic Technique',
                'slug' => 'تکنیک هنری',
                'description' => 'Artwork showcasing specific artistic styles, methods, or visual effects',
                'color_hex' => '#7C3AED',
                'parent_id' => null,
                'sort_order' => 15,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Wallpaper',
                'slug' => 'والپیپر',
                'description' => 'Artwork designed specifically for use as desktop or mobile backgrounds',
                'color_hex' => '#059669',
                'parent_id' => null,
                'sort_order' => 16,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Cartoon Realism',
                'slug' => 'رئالیسم کارتونی',
                'description' => 'Realistic interpretations of traditionally cartoon characters',
                'color_hex' => '#D97706',
                'parent_id' => null,
                'sort_order' => 17,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Wildlife Photography',
                'slug' => 'عکاسی حیات وحش',
                'description' => 'Realistic depictions of animals in their natural habitats',
                'color_hex' => '#65A30D',
                'parent_id' => null,
                'sort_order' => 18,
                'is_active' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        DB::table('categories')->insert($categories);
    }
}