<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class PromptTemplatesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $templates = [
            [
                'title' => 'Playful Bubble Gum Portrait',
                'description' => 'A cinematic urban portrait of a girl blowing bubble gum playfully',
                'content' => 'She`s blowing bubble gum playfully toward the camera. Slight visual noise and grain texture, subtle distortion from the lens, cheeky expression, urban residential vibe, cinematic framing, high contrast shadows',
                'image_path' => 'https://image.lexica.art/md2/d2994f02-9175-4f1a-9e86-527d570a2bb1',
                'ai_model_id' => 1,
                'category_id' => 1,
                'user_id' => 1,
                'total_likes' => 0,
                'total_views' => 0,
                'is_public' => true,
                'metadata' => json_encode(['style' => 'cinematic', 'mood' => 'playful', 'environment' => 'urban']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Realistic Misty Cosplay',
                'description' => 'Photorealistic Misty from Pokemon in a dark aesthetic setting',
                'content' => 'A real life photo photo of misty from pkemon. She is smiling (head sligtly tilt, holding a half white half red baseball. The other hand is making a peace sign.\nThere is two star fishes beside her. dark aesthetic.',
                'image_path' => 'https://image.lexica.art/md2/8026208b-5d3f-45d8-a9cd-08d35bea0f0d',
                'ai_model_id' => 1,
                'category_id' => 2,
                'user_id' => 1,
                'total_likes' => 0,
                'total_views' => 0,
                'is_public' => true,
                'metadata' => json_encode(['character' => 'Misty', 'franchise' => 'Pokemon', 'style' => 'photorealistic']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Urban Bubble Gum Scene',
                'description' => 'Cinematic urban portrait with playful bubble gum moment',
                'content' => 'She`s blowing bubble gum playfully toward the camera. Slight visual noise and grain texture, subtle distortion from the lens, cheeky expression, urban residential vibe, cinematic framing, high contrast shadows',
                'image_path' => 'https://image.lexica.art/md2/0abe3caa-8b60-48a0-969d-6902c2c6168f',
                'ai_model_id' => 1,
                'category_id' => 1,
                'user_id' => 1,
                'total_likes' => 0,
                'total_views' => 0,
                'is_public' => true,
                'metadata' => json_encode(['style' => 'cinematic', 'mood' => 'playful', 'environment' => 'urban']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Panda Driving Sports Car',
                'description' => 'Absurd scene of a panda driving erratically at night',
                'content' => 'Footage of a panda driving a sports car erratically on a highway at night (live action style)',
                'image_path' => 'https://image.lexica.art/md2/84b566e6-5227-4dce-a832-dbff3efd2127',
                'ai_model_id' => 1,
                'category_id' => 3,
                'user_id' => 1,
                'total_likes' => 0,
                'total_views' => 0,
                'is_public' => true,
                'metadata' => json_encode(['absurd' => true, 'animals' => 'panda', 'action' => 'driving']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Anime College Girl Selfie',
                'description' => 'Close-up anime style selfie of Japanese college woman',
                'content' => 'anime, close up selfie-shots of japanese woman in college',
                'image_path' => 'https://image.lexica.art/md2/1ef84da0-a4e5-4346-890d-377a24dec728',
                'ai_model_id' => 1,
                'category_id' => 4,
                'user_id' => 1,
                'total_likes' => 0,
                'total_views' => 0,
                'is_public' => true,
                'metadata' => json_encode(['style' => 'anime', 'type' => 'selfie', 'subject' => 'college girl']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => '90s Anime Pilot Girl',
                'description' => 'Moody lighting portrait of a brunette pilot in 90s anime style',
                'content' => 'A beautiful brunette pilot girl, beautiful, moody lighting, 90s anime minimal masterpiexce',
                'image_path' => 'https://image.lexica.art/md2/5f810a1e-605d-4116-9c26-2b37642e3c16',
                'ai_model_id' => 1,
                'category_id' => 4,
                'user_id' => 1,
                'total_likes' => 0,
                'total_views' => 0,
                'is_public' => true,
                'metadata' => json_encode(['era' => '90s', 'style' => 'anime', 'occupation' => 'pilot']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => '90s Classroom Crossover',
                'description' => 'Minecraft Steve, Yoshi, Sonic, Trump and Harry Potter in classroom',
                'content' => 'A 90\'s classroom with the following characters sitting on desks blocky Minecraft Steve, Yoshi, Sonic, Donald Trump, and Harry Potter.',
                'image_path' => 'https://image.lexica.art/md2/26458208-3252-44a2-867a-968f53496e0f',
                'ai_model_id' => 1,
                'category_id' => 5,
                'user_id' => 1,
                'total_likes' => 0,
                'total_views' => 0,
                'is_public' => true,
                'metadata' => json_encode(['crossover' => true, 'characters' => ['Minecraft Steve', 'Yoshi', 'Sonic', 'Trump', 'Harry Potter']]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Kirby Target Employee ID',
                'description' => 'Awkward employee photo of Kirby as Target team member',
                'content' => 'Awkward employee ID badge photo of Kirby as new Target team member, too close to camera, red vest barely fitting his round body, name tag just says "KIRBY." Photo of Kirby wearing the badge.',
                'image_path' => 'https://image.lexica.art/md2/25f8a7d1-5dcc-44df-ae8b-655efd9de2d9',
                'ai_model_id' => 1,
                'category_id' => 6,
                'user_id' => 1,
                'total_likes' => 0,
                'total_views' => 0,
                'is_public' => true,
                'metadata' => json_encode(['character' => 'Kirby', 'situation' => 'workplace', 'mood' => 'awkward']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Gothic Rooftop Contemplation',
                'description' => 'Cinematic shot of woman on Zurich rooftop with gothic aesthetic',
                'content' => 'Shot with ARRI ALEXA Mini LF, medium shot, low-angle perspective. A young woman with straight black hair and blunt bangs sits quietly on the edge of a rooftop, overlooking the cloudy cityscape of Zurich. She wears a sheer black lace dress, black transparent tights, and dark lipstick, creating a striking contrast against the muted, overcast sky. Her posture is calm and contemplative, with her gaze lost in the distance. The cool tones of the cloudy daylight enhance the gothic and delicate aesthetic of her look, while the urban background adds depth to the scene.',
                'image_path' => 'https://image.lexica.art/md2/83042c0d-90f7-4e8d-a310-280d7f9a0fb4',
                'ai_model_id' => 1,
                'category_id' => 1,
                'user_id' => 1,
                'total_likes' => 0,
                'total_views' => 0,
                'is_public' => true,
                'metadata' => json_encode(['style' => 'cinematic', 'aesthetic' => 'gothic', 'location' => 'Zurich']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => '80s Anime Elf Ballroom',
                'description' => 'Worried elf woman in dragon pattern ballgown, 80s anime style',
                'content' => 'beautiful elf woman with very long, wavy copper orange hair. she\'s wearing a beautiful ballgown with dragon patterns on it. she\'s standing in the doorway to a ballroom where people are dancing. she\'s looking over her shoulder. her facial expression is worried. she has freckles. very beautiful elf woman with very long copper red hair. her eyes are a grayish blue.. 80s anime style',
                'image_path' => 'https://image.lexica.art/md2/f068b476-a4c7-4a22-a6c0-01a105c1d098',
                'ai_model_id' => 1,
                'category_id' => 4,
                'user_id' => 1,
                'total_likes' => 0,
                'total_views' => 0,
                'is_public' => true,
                'metadata' => json_encode(['era' => '80s', 'style' => 'anime', 'fantasy' => 'elf']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Patrick Star Fancy Date',
                'description' => 'Grunge analog photo of Patrick Star on a date in restaurant',
                'content' => 'A grungy, analog 11 photo of Patrick Star from spongebob in on a date with the POV in a fancy restaurant. he is holding the POV\'s hand and smirking. The photo was taken with flash, unedited, with a gritty, raw look',
                'image_path' => 'https://image.lexica.art/md2/bb7cc569-d8ce-462e-9e24-052e0c4164d2',
                'ai_model_id' => 1,
                'category_id' => 6,
                'user_id' => 1,
                'total_likes' => 0,
                'total_views' => 0,
                'is_public' => true,
                'metadata' => json_encode(['character' => 'Patrick Star', 'style' => 'grunge', 'situation' => 'date']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'White Haired Girl with Cat',
                'description' => 'Cute selfie of white-haired woman with orange cat',
                'content' => 'A 22-year-old woman with long white hair selfie photo with an orange cat. silly and cute',
                'image_path' => 'https://image.lexica.art/md2/97f0a6ce-891b-4c12-99ac-365180967572',
                'ai_model_id' => 1,
                'category_id' => 7,
                'user_id' => 1,
                'total_likes' => 0,
                'total_views' => 0,
                'is_public' => true,
                'metadata' => json_encode(['subject' => 'woman', 'pet' => 'cat', 'mood' => 'cute']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'McDonald\'s Hamburger Building',
                'description' => 'Realistic giant hamburger-shaped McDonald\'s store in Shanghai',
                'content' => 'A realistic giant hamburger-shaped multi-level pop-up store on a busy city street, branded with the McDonald\'s logo, each layer of the burger is a floor with windows, McDonald\'s workers visible preparing burgers inside, lively urban atmosphere, realistic lighting, Shanghai skyline in the background, photorealistic tilt shift photo',
                'image_path' => 'https://image.lexica.art/md2/bfde50df-9300-4cd3-9aec-5a382b617674',
                'ai_model_id' => 1,
                'category_id' => 8,
                'user_id' => 1,
                'total_likes' => 0,
                'total_views' => 0,
                'is_public' => true,
                'metadata' => json_encode(['architecture' => 'creative', 'brand' => 'McDonald\'s', 'location' => 'Shanghai']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Fascist President Portrait',
                'description' => 'Portrait of a fascist president',
                'content' => 'the fascist president',
                'image_path' => 'https://image.lexica.art/md2/4b9aefa1-5f91-44cf-9060-607ca0f2e226',
                'ai_model_id' => 1,
                'category_id' => 9,
                'user_id' => 2,
                'total_likes' => 0,
                'total_views' => 0,
                'is_public' => true,
                'metadata' => json_encode(['political' => true, 'style' => 'portrait']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => '80s Anime Protagonist',
                'description' => '80s anime character lighting cigarette in front of Tower Records',
                'content' => '80s anime, protagonist lighting a cigarettein front of tower records',
                'image_path' => 'https://image.lexica.art/md2/87a6d493-0390-424a-a2c2-f959d7445e2f',
                'ai_model_id' => 1,
                'category_id' => 4,
                'user_id' => 1,
                'total_likes' => 0,
                'total_views' => 0,
                'is_public' => true,
                'metadata' => json_encode(['era' => '80s', 'style' => 'anime', 'action' => 'smoking']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Nintendo Kendrick Lamar Album',
                'description' => 'Kendrick Lamar style album art featuring Nintendo characters',
                'content' => 'kendrick lamar style album art but its nintendo characters',
                'image_path' => 'https://image.lexica.art/md2/e180853a-9ddc-4b28-86e2-00d0c4763540',
                'ai_model_id' => 1,
                'category_id' => 10,
                'user_id' => 3,
                'total_likes' => 0,
                'total_views' => 0,
                'is_public' => true,
                'metadata' => json_encode(['music' => 'album art', 'style' => 'Kendrick Lamar', 'characters' => 'Nintendo']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Minimalist Japan Photography',
                'description' => 'Minimalist blissful Japanese scene shot on Leica',
                'content' => 'minimalist bliss. japan. shot on leica.',
                'image_path' => 'https://image.lexica.art/md2/bfffdce9-d4d0-406f-9fb0-5fce4b71972c',
                'ai_model_id' => 1,
                'category_id' => 11,
                'user_id' => 1,
                'total_likes' => 0,
                'total_views' => 0,
                'is_public' => true,
                'metadata' => json_encode(['style' => 'minimalist', 'location' => 'Japan', 'camera' => 'Leica']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Gritty Elsa Selfie Alley',
                'description' => 'Grainy iPhone photo of Elsa taking moody selfie in abandoned alley',
                'content' => 'Grainy iPhone 6 flash photo of Elsa from Frozen taking a moody selfie in a dark, abandoned alleyway. She stands against a crumbling, graffiti-sprayed brick wall, the fluorescent paint peeling and flaking under years of neglect. Elsa\'s platinum-blonde hair is loosely tied back, with two soft strands falling across her pale, freckled face. She wears a glittering but slightly torn silver-blue gown, its shimmer dulled under layers of city grime. A thin silver chain necklace glints under the harsh flash.\n\nElsa holds a glass of wine in one hand. Her other hand lifts the phone for the shot, and the flash bounces sharply off her pale skin, bleaching her features and casting deep shadows into the corners of the alley. A cigarette butt lies crushed by her silver heel at the bottom of the frame.\n\nHer expression is sharp, melancholic, and defiantly amused — a fallen queen savoring a moment of ruined beauty. The ground is cracked concrete littered with shattered glass. The grainy flash photo captures a raw, analog, unfiltered snapshot — rich with a 90s VHS nostalgia, grungy texture, and the heavy, timeless weight of forgotten dreams.',
                'image_path' => 'https://image.lexica.art/md2/2b1187b1-25f1-4d40-90ca-acd90b18c2a8',
                'ai_model_id' => 1,
                'category_id' => 6,
                'user_id' => 1,
                'total_likes' => 0,
                'total_views' => 0,
                'is_public' => true,
                'metadata' => json_encode(['character' => 'Elsa', 'style' => 'grunge', 'mood' => 'melancholic']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Wendy\'s Waitress Casual Photo',
                'description' => 'Ordinary iPhone photo of Chinese waitress at Wendy\'s',
                'content' => 'An extremely ordinary iPhone photo taken from a low angle, with no clear subject or composition, looking like a careless snapshot. The overall effect is very mediocre, as if it were an accidental photo.\n\nThis is a 22-year-old Chinese girl with striking black hair styled in a beautiful ponytail that moves slightly as she moves, tied with a bright blue ribbon. Her fair skin is dotted with light freckles on her cheeks, adding to her fresh, youthful charm. Her smile is gentle and sincere, lighting up her face with a quiet warmth. Her eyes are round and expressive, sparkling with a hint of mischief and kindness. She wears a blue-and-white gingham checkered dress with short, puffy sleeves and a low square neckline, paired with a white apron that has a lace trim tied over it. She accessorizes with red-and-white striped arm warmers and matching thigh-high stockings, adding a playful, whimsical touch to her look. Her overall presence is vibrant, yet naturally graceful, nostalgic yet lively.\n\nShe sits on top of a red table at an outdoor seating area of a fast-food restaurant, with the Wendy\'s sign visible beside the building. She leans slightly, knees bent, hugging her legs. She is barefoot, with pale blue-painted nails resting on the bench seat. A fast food bag sits next to her on the table.',
                'image_path' => 'https://image.lexica.art/md2/a8ba0233-6957-4324-b722-0602761dc3ad',
                'ai_model_id' => 1,
                'category_id' => 7,
                'user_id' => 1,
                'total_likes' => 0,
                'total_views' => 0,
                'is_public' => true,
                'metadata' => json_encode(['style' => 'casual', 'location' => 'Wendy\'s', 'mood' => 'playful']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Sci-Fi Mammoth Painting',
                'description' => 'Mammoth with sci-fi twist in oil painting style',
                'content' => 'Mammoth with science fiction twist  - oil painitng style of Bernie Wrghtson and Wally Wood',
                'image_path' => 'https://image.lexica.art/md2/dce05551-326b-437e-afc1-4b9a5bca0902',
                'ai_model_id' => 1,
                'category_id' => 12,
                'user_id' => 4,
                'total_likes' => 0,
                'total_views' => 0,
                'is_public' => true,
                'metadata' => json_encode(['style' => 'oil painting', 'subject' => 'mammoth', 'genre' => 'sci-fi']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Anime Girl 5 Minutes',
                'description' => 'Japanese anime girl enthusiastically saying "5 minutes"',
                'content' => 'Japanese anime-style illustration of a lively woman with short hair and straight-cut bangs. She dramatically extends her open hand forward, with an exaggerated, cheerful manga-style smile, as if enthusiastically insisting "5 minutes". Her eyes sparkle brightly with lively energy. Behind her are a bookshelf, a desk, and a clock, forming a cozy and relaxed interior scene. A cat sits quietly nearby, adding warmth and charm. The color palette is vivid and pop-inspired, with cheerful tones, but the overall mood remains calm and soothing. The composition features clean, expressive linework and soft shading, balancing vibrant energy with a gentle atmosphere.',
                'image_path' => 'https://image.lexica.art/md2/3175cf0b-065b-4639-a403-c4ec8b97b138',
                'ai_model_id' => 1,
                'category_id' => 4,
                'user_id' => 1,
                'total_likes' => 0,
                'total_views' => 0,
                'is_public' => true,
                'metadata' => json_encode(['style' => 'anime', 'mood' => 'cheerful', 'action' => 'gesturing']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Sailor Moon Tomb Raider Selfie',
                'description' => 'iPhone selfie with Sailor Moon and Tomb Raider characters',
                'content' => 'iPhone selfie, with no clear subject or sense of composition—just like a casual snapshot taken at random. The photo is  The main characters are Sailor Moon and Tomb Raider.',
                'image_path' => 'https://image.lexica.art/md2/5d350d43-7bba-4fc3-8ae8-c8dd389658a2',
                'ai_model_id' => 1,
                'category_id' => 5,
                'user_id' => 5,
                'total_likes' => 0,
                'total_views' => 0,
                'is_public' => true,
                'metadata' => json_encode(['crossover' => true, 'characters' => ['Sailor Moon', 'Tomb Raider'], 'style' => 'selfie']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Ultra Detailed Giraffe',
                'description' => 'Most beautiful and detailed giraffe portrait in 64k resolution',
                'content' => 'The most beautiful, amazing and awe inspiring giraffe, insane detail, ultra sharp focus, 64k',
                'image_path' => 'https://image.lexica.art/md2/7b334c62-d5bc-4fa4-9eaa-db2232c57fd6',
                'ai_model_id' => 1,
                'category_id' => 13,
                'user_id' => 1,
                'total_likes' => 0,
                'total_views' => 0,
                'is_public' => true,
                'metadata' => json_encode(['animal' => 'giraffe', 'quality' => '64k', 'detail' => 'ultra sharp']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Kirby Boiler Room DJ',
                'description' => 'Cute Kirby DJ set with bodyguards in boiler room',
                'content' => 'cute Kirby boiler room dj set, wearing black sunglasses, donkey kong and king dededee are his bodyguards. pappaeazzi flash photo, does not want to be photographed.. motion blur, blurry, grainy. TMZ logo in corner. crowds in the background, flashes from camera going off, g',
                'image_path' => 'https://image.lexica.art/md2/519c0daf-2d0d-4440-af97-a2da7c4f6e8c',
                'ai_model_id' => 1,
                'category_id' => 6,
                'user_id' => 3,
                'total_likes' => 0,
                'total_views' => 0,
                'is_public' => true,
                'metadata' => json_encode(['character' => 'Kirby', 'situation' => 'DJ', 'style' => 'paparazzi']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Sailor Saturn Cosplay Selfie',
                'description' => 'Realistic selfie of woman cosplaying as Sailor Saturn',
                'content' => 'A realistic selfie-style portrait of a woman cosplaying as Sailor Saturn, captured from the perspective of her outstretched phone. Her arm is extended toward the camera, holding the phone at a slight high angle. She wears a detailed and well-fitted version of Sailor Saturn\'s violet and white sailor uniform, complete with gloves, pleated skirt, and a shimmering silver brooch on the chest bow. Her short, sleek black hair with violet tones frames her face, and she wears a silver tiara with a purple gem. Her violet contact lenses glow subtly, and she smiles softly or gives a calm, introspective expression. The Silence Glaive is visible in the background, leaned against a wall or resting nearby. The background features a casual convention hall, softly lit room, or a starry aesthetic filter overlay. Lighting is natural and flattering, with smooth skin tones and reflective detail on her costume. The composition captures a balance of realism, character fidelity, and selfie-era charm. She is focus of the frame',
                'image_path' => 'https://image.lexica.art/md2/ffe2ee8d-e516-468d-9137-178d92014f6e',
                'ai_model_id' => 1,
                'category_id' => 2,
                'user_id' => 1,
                'total_likes' => 0,
                'total_views' => 0,
                'is_public' => true,
                'metadata' => json_encode(['cosplay' => 'Sailor Saturn', 'style' => 'realistic', 'type' => 'selfie']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Nintendo Cinematic Poster',
                'description' => '2010s cinematic minimal movie poster for Nintendo characters',
                'content' => '2010s cinematic minimal movie poster that goes hard but its for nintendo characters',
                'image_path' => 'https://image.lexica.art/md2/209fdd75-0794-48fe-b025-ca57e2d16993',
                'ai_model_id' => 1,
                'category_id' => 14,
                'user_id' => 3,
                'total_likes' => 0,
                'total_views' => 0,
                'is_public' => true,
                'metadata' => json_encode(['style' => 'cinematic', 'minimal' => true, 'characters' => 'Nintendo']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => '80s Anime Dark Prince',
                'description' => 'Dark prince character in 80s anime minimal masterpiece style',
                'content' => 'Dark prince, 80s anime, minimal masterpiece',
                'image_path' => 'https://image.lexica.art/md2/0fd8e3dc-aa4c-418a-99c4-ec0707ad3a99',
                'ai_model_id' => 1,
                'category_id' => 4,
                'user_id' => 1,
                'total_likes' => 0,
                'total_views' => 0,
                'is_public' => true,
                'metadata' => json_encode(['era' => '80s', 'style' => 'anime', 'character' => 'dark prince']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Arthur Morgan Double Exposure',
                'description' => 'Double exposure artwork of Arthur Morgan with frontier landscapes',
                'content' => 'Double exposure, Midjourney style, merging, blending, overlay double exposure image, Double Exposure style,\nAn exceptional masterpiece by Yukisakura revealing a fantastic double exposure composition of Arthur Morgan\'s silhouette harmoniously intertwined with the visually striking, rugged landscapes of the American frontier during a cold winter. Snow-covered pine forests, frosty mountain peaks, and a lone horse cutting through the trail echo outward through the fabric of his figure, adding layers of narrative and solitude. Beautiful tension builds as the stark monochrome background maintains razor-sharp contrast, drawing all focus to the richly layered double exposure. Characterized by its vibrant full-color scheme within Arthur Morgan\'s silhouette and crisp, deliberate lines that trace every contour with emotional precision. (Detailed1.45). (Detailed background1.4).',
                'image_path' => 'https://image.lexica.art/md2/8d500d95-4941-40fa-9d76-b2003e30f77e',
                'ai_model_id' => 1,
                'category_id' => 15,
                'user_id' => 1,
                'total_likes' => 0,
                'total_views' => 0,
                'is_public' => true,
                'metadata' => json_encode(['technique' => 'double exposure', 'character' => 'Arthur Morgan', 'style' => 'artistic']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Coffee Personification Portrait',
                'description' => 'Handsome young man as personification of coffee in golden light',
                'content' => 'Canon EOS DSLR, 85mm f1.4, extremely handsome young white man in his early 20s, personification of coffee, soft wavy dark brown hair, deep espresso-colored eyes, flawless warm skin, holding a steaming ceramic coffee cup in one hand, wearing a relaxed linen shirt slightly unbuttoned, sitting by a cafe window bathed in golden morning sunlight, subtle steam rising around his face, gentle smile with a touch of mystery, cinematic lighting, romantic',
                'image_path' => 'https://image.lexica.art/md2/1b2880d6-99b1-4a18-b474-3b6346fa2c71',
                'ai_model_id' => 1,
                'category_id' => 1,
                'user_id' => 1,
                'total_likes' => 0,
                'total_views' => 0,
                'is_public' => true,
                'metadata' => json_encode(['style' => 'cinematic', 'concept' => 'personification', 'subject' => 'coffee']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Asuka Langley Analog Portrait',
                'description' => 'Analog portrait photo of Asuka Langley Soryu in lab environment',
                'content' => 'Analog portrait photo of Asuka Langley Soryu, Portra 400, detailed environment, inside the LAB',
                'image_path' => 'https://image.lexica.art/md2/1a13e40e-5fb6-4dbe-9a99-79d53ee2b2a6',
                'ai_model_id' => 1,
                'category_id' => 2,
                'user_id' => 1,
                'total_likes' => 0,
                'total_views' => 0,
                'is_public' => true,
                'metadata' => json_encode(['character' => 'Asuka Langley', 'style' => 'analog', 'film' => 'Portra 400']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => '90s Anime SF Onsen Poster',
                'description' => '1990s anime poster for Japanese style science fiction onsen',
                'content' => '1990s anime poster for sf japanese style onsen, blow my mind',
                'image_path' => 'https://image.lexica.art/md2/e27e8cf8-a27e-41f6-a958-2702d6d3225b',
                'ai_model_id' => 1,
                'category_id' => 4,
                'user_id' => 1,
                'total_likes' => 0,
                'total_views' => 0,
                'is_public' => true,
                'metadata' => json_encode(['era' => '90s', 'style' => 'anime', 'theme' => 'onsen']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Kirby iOS Wallpaper',
                'description' => 'Wallpaper design featuring Kirby for iOS devices',
                'content' => 'kirby wallpaper for iOS',
                'image_path' => 'https://image.lexica.art/md2/e4519e38-db08-4d2a-89af-df4affbc2fac',
                'ai_model_id' => 1,
                'category_id' => 16,
                'user_id' => 1,
                'total_likes' => 0,
                'total_views' => 0,
                'is_public' => true,
                'metadata' => json_encode(['character' => 'Kirby', 'purpose' => 'wallpaper', 'platform' => 'iOS']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Minions Trench Coat Disguise',
                'description' => 'Ring doorbell video of three Minions attempting to pose as adult',
                'content' => 'Ring doorbell video of three Minions in trench coat attempting to pose as one adult human',
                'image_path' => 'https://image.lexica.art/md2/b941d0b2-cdbe-4c80-b871-b30ed685ce2c',
                'ai_model_id' => 1,
                'category_id' => 3,
                'user_id' => 1,
                'total_likes' => 0,
                'total_views' => 0,
                'is_public' => true,
                'metadata' => json_encode(['characters' => 'Minions', 'situation' => 'disguise', 'style' => 'doorbell']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Katsuhiro Otomo Style Astronaut',
                'description' => 'Astronaut in space designed in Katsuhiro Otomo artistic style',
                'content' => 'Design an astronaut in Katsuhiro Otomo style flying in dark space.',
                'image_path' => 'https://image.lexica.art/md2/5ac5ef33-12d8-4180-b5c0-f8d603c9d15f',
                'ai_model_id' => 1,
                'category_id' => 4,
                'user_id' => 1,
                'total_likes' => 0,
                'total_views' => 0,
                'is_public' => true,
                'metadata' => json_encode(['artist' => 'Katsuhiro Otomo', 'subject' => 'astronaut', 'environment' => 'space']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Realistic Calvin and Hobbes',
                'description' => 'Realistic version of Calvin and Hobbes characters',
                'content' => 'a realistic version of calvin and hobbes',
                'image_path' => 'https://image.lexica.art/md2/12f53fd6-7f81-48a3-a8ee-22fd0481b4d0',
                'ai_model_id' => 1,
                'category_id' => 17,
                'user_id' => 1,
                'total_likes' => 0,
                'total_views' => 0,
                'is_public' => true,
                'metadata' => json_encode(['characters' => 'Calvin and Hobbes', 'style' => 'realistic']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Cat Selfie at Big Ben',
                'description' => 'Realistic cat taking selfie in front of Big Ben with raincoat',
                'content' => 'A realistic gray cat taking a selfie in front of Big Ben in London, raindrops on its fur, wearing a miniature raincoat',
                'image_path' => 'https://image.lexica.art/md2/8a3ddf26-4a72-4501-94d4-8e707d4fb857',
                'ai_model_id' => 1,
                'category_id' => 7,
                'user_id' => 1,
                'total_likes' => 0,
                'total_views' => 0,
                'is_public' => true,
                'metadata' => json_encode(['animal' => 'cat', 'location' => 'Big Ben', 'style' => 'selfie']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Minions NYC Paparazzi Photo',
                'description' => 'TMZ paparazzi photo of Minions getting late night snack in NYC',
                'content' => 'TMZ papparazzi photo of 3 minions, flash photo, at night, gritty nyc streets, getting a late night snack',
                'image_path' => 'https://image.lexica.art/md2/3ec93c9a-ebf4-45e2-9afb-1857f9c0f864',
                'ai_model_id' => 1,
                'category_id' => 6,
                'user_id' => 1,
                'total_likes' => 0,
                'total_views' => 0,
                'is_public' => true,
                'metadata' => json_encode(['characters' => 'Minions', 'style' => 'paparazzi', 'location' => 'NYC']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Kirby Club Exit Paparazzi',
                'description' => 'Cute Kirby leaving club at night with paparazzi attention',
                'content' => 'cute Kirby leaving the club at night, wearing black sunglasses, pappaeazzi flash photo, does not want to be photographed.. motion blur, blurry, grainy. TMZ logo in corner. crowds in the background, flashes from camera going off.',
                'image_path' => 'https://image.lexica.art/md2/d498bab9-72d3-4c85-a858-e0728a092de7',
                'ai_model_id' => 1,
                'category_id' => 6,
                'user_id' => 1,
                'total_likes' => 0,
                'total_views' => 0,
                'is_public' => true,
                'metadata' => json_encode(['character' => 'Kirby', 'situation' => 'nightlife', 'style' => 'paparazzi']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'MarioKart Cinematic Poster',
                'description' => 'Cinematic movie poster design for MarioKart',
                'content' => 'cinematic mariokart movie poster',
                'image_path' => 'https://image.lexica.art/md2/be365f05-8158-40bc-8de4-20a388cc49d7',
                'ai_model_id' => 1,
                'category_id' => 14,
                'user_id' => 3,
                'total_likes' => 0,
                'total_views' => 0,
                'is_public' => true,
                'metadata' => json_encode(['game' => 'MarioKart', 'style' => 'cinematic', 'purpose' => 'poster']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Darth Vader Wedding Photography',
                'description' => 'Wedding photography of Darth Vader walking daughter down aisle',
                'content' => 'Wedding photography of Darth Vader walking his daughter down the aisle, still breathing heavily through his mask but dabbing a tear with a white handkerchief',
                'image_path' => 'https://image.lexica.art/md2/21b5cd73-74d8-44fb-9111-a8756818a805',
                'ai_model_id' => 1,
                'category_id' => 6,
                'user_id' => 1,
                'total_likes' => 0,
                'total_views' => 0,
                'is_public' => true,
                'metadata' => json_encode(['character' => 'Darth Vader', 'situation' => 'wedding', 'mood' => 'emotional']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Nightvision Chimp Trailcam',
                'description' => 'Trailcam footage of chimps captured with nightvision',
                'content' => 'trailcam footage, chimps, nightvision',
                'image_path' => 'https://image.lexica.art/md2/1ed7aad5-131e-4843-9037-59011703875c',
                'ai_model_id' => 1,
                'category_id' => 18,
                'user_id' => 2,
                'total_likes' => 0,
                'total_views' => 0,
                'is_public' => true,
                'metadata' => json_encode(['animals' => 'chimps', 'equipment' => 'trailcam', 'lighting' => 'nightvision']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Musk Trump Gaming Session',
                'description' => 'Unremarkable iPhone selfie of Elon Musk and Trump gaming',
                'content' => 'An extremely unremarkable, blurry iPhone selfie photo with no proper framing or focus — a badly timed, accidental-looking snapshot.\nThe photo has mild motion blur and harsh, uneven lighting from a flickering ceiling lamp.\nThe camera angle is awkward and tilted, like the phone was slipping from someone\'s hand mid-shot.\nIn the scene\nElon Musk sits slouched on a worn-out couch covered in random blankets, wearing an oversized T-shirt with a ketchup stain, playing a dusty old Xbox 360 controller with intense focus.\nNext to him, trump is half-asleep, wrapped in a giant burrito blanket, drooling slightly onto a TV remote.\nThe room is cluttered with empty pizza boxes, laundry piles, and a few knocked-over cans of Monster Energy drink.\nThe overall mood is extremely mundane, chaotic, and mildly depressing in an oddly humorous way.',
                'image_path' => 'https://image.lexica.art/md2/5dac4f26-75a7-4276-8b75-32a38ed3f8dd',
                'ai_model_id' => 1,
                'category_id' => 3,
                'user_id' => 1,
                'total_likes' => 0,
                'total_views' => 0,
                'is_public' => true,
                'metadata' => json_encode(['people' => ['Elon Musk', 'Trump'], 'situation' => 'gaming', 'style' => 'casual']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Jacked Anime Girl CrossFit',
                'description' => 'Anime girl with muscular physique competing in CrossFit',
                'content' => 'a jacked anime girl competing in a CrossFit competition',
                'image_path' => 'https://image.lexica.art/md2/71a47023-e031-4e75-9026-5a12fa94c81d',
                'ai_model_id' => 1,
                'category_id' => 4,
                'user_id' => 1,
                'total_likes' => 0,
                'total_views' => 0,
                'is_public' => true,
                'metadata' => json_encode(['style' => 'anime', 'sport' => 'CrossFit', 'body' => 'muscular']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Kiki Delivery Service Portrait',
                'description' => 'High-resolution realistic portrait of Kiki from Delivery Service',
                'content' => 'The high-resolution realistic portrait of Kiki in "The Witch Home Delivery Service" depicts a young Japanese beauty cosplayer, with delicate facial features, flowing skin, delicate facial texture, and light and natural makeup, she is relaxed riding a broomstick through the sunny sky wearing a red bow on her head, wearing a black dress and carrying a brown leather satchel on her back, flying on a broomstick with the black cat Gigi, their figures soar over the sparkling coastal water, dynamic wind effects',
                'image_path' => 'https://image.lexica.art/md2/e7d6e85d-0ce0-49b1-b8a1-813e912fd90d',
                'ai_model_id' => 1,
                'category_id' => 2,
                'user_id' => 1,
                'total_likes' => 0,
                'total_views' => 0,
                'is_public' => true,
                'metadata' => json_encode(['character' => 'Kiki', 'movie' => 'Kiki\'s Delivery Service', 'style' => 'realistic']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Alien Neon Heart Art',
                'description' => 'Photorealistic alien made of obsidian holding neon heart in glass cube',
                'content' => 'an alien made of obsidian and slimy darkness with glowing white eyes stands inside a thin translucent giant glass cube in the middle of a red neon void. inside the cube he holds a melting small organic human heart made of neon white liquid. photorealistic',
                'image_path' => 'https://image.lexica.art/md2/1dbfc2d4-f56a-4097-9c32-2a1c9f91e2dd',
                'ai_model_id' => 1,
                'category_id' => 12,
                'user_id' => 1,
                'total_likes' => 0,
                'total_views' => 0,
                'is_public' => true,
                'metadata' => json_encode(['subject' => 'alien', 'style' => 'photorealistic', 'elements' => ['obsidian', 'neon', 'glass']]),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Cookie Monster Presidential Portrait',
                'description' => 'Presidential portrait of Cookie Monster in Oval Office',
                'content' => 'Presidential Portrait photo of Cookie Monster in the Oval Office. He is holding up a signed piece of paper which reads "NO TARIFFS ON COOKIES FROM CHINA" in a LARGE text. Is is the central part of the frame. In his other hand he is holding a cookie.',
                'image_path' => 'https://image.lexica.art/md2/b1f1d087-823f-4ebb-a691-daf567b2f7d6',
                'ai_model_id' => 1,
                'category_id' => 6,
                'user_id' => 1,
                'total_likes' => 0,
                'total_views' => 0,
                'is_public' => true,
                'metadata' => json_encode(['character' => 'Cookie Monster', 'setting' => 'Oval Office', 'theme' => 'political']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => '90s Anime Scratchy Style',
                'description' => 'Vintage 90s anime with scratchy pen strokes and angular shapes',
                'content' => 'Vintage 90s anime, Scratchy pen strokes, blind contour, perspective closeup, beautiful girl, face in darkness, stark hatch shaded sketchy scribbly, ink, strong angular shapes, woodcut shading, pen strokes, pouty lips, hungry eyes, minimalist realistic, proportions',
                'image_path' => 'https://image.lexica.art/md2/19eff5e4-34da-46bb-98c5-94f9949a8c40',
                'ai_model_id' => 1,
                'category_id' => 4,
                'user_id' => 1,
                'total_likes' => 0,
                'total_views' => 0,
                'is_public' => true,
                'metadata' => json_encode(['era' => '90s', 'style' => 'sketchy', 'technique' => 'pen strokes']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Capybara Ocean Swimming',
                'description' => 'Cute capybara swimming in ocean with Portra 400 film style',
                'content' => 'a cute capybara swimming in the ocean, portra 400, wide angle shot, majestic fog',
                'image_path' => 'https://image.lexica.art/md2/73c54bb1-756b-437e-8337-e55c8b6c28ed',
                'ai_model_id' => 1,
                'category_id' => 13,
                'user_id' => 1,
                'total_likes' => 0,
                'total_views' => 0,
                'is_public' => true,
                'metadata' => json_encode(['animal' => 'capybara', 'film' => 'Portra 400', 'environment' => 'ocean']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Trump Evil Anime Style',
                'description' => 'Donald Trump portrayed in evil anime style',
                'content' => 'trump in evil anime style',
                'image_path' => 'https://image.lexica.art/md2/b0422224-fe8d-492a-81f7-06f117ae5e02',
                'ai_model_id' => 1,
                'category_id' => 4,
                'user_id' => 1,
                'total_likes' => 0,
                'total_views' => 0,
                'is_public' => true,
                'metadata' => json_encode(['person' => 'Trump', 'style' => 'anime', 'mood' => 'evil']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Phonk Song Poster Design',
                'description' => 'Phonk song poster with grungy analog photo style',
                'content' => 'Phonk song poster of a Grungy analog photo, late 90s/early 2000s style,  Ring camera footage EPIC Games character a soldier In stealth mode, night time, black ops cinema influence, HDR10+',
                'image_path' => 'https://image.lexica.art/md2/bbb0affb-b370-4c0d-912c-f614f34cf4bc',
                'ai_model_id' => 1,
                'category_id' => 10,
                'user_id' => 6,
                'total_likes' => 0,
                'total_views' => 0,
                'is_public' => true,
                'metadata' => json_encode(['music' => 'Phonk', 'style' => 'grungy', 'era' => '90s-2000s']),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]
        ];

        DB::table('prompt_templates')->insert($templates);
    }
}