INSERT INTO categories (name, slug, description, color_hex, parent_id, sort_order, is_active, created_at, updated_at) VALUES
('Cinematic Portrait', 'پرتره سینمایی', 'Stylish, professionally composed character portraits with dramatic lighting and atmosphere', '#3B82F6', NULL, 1, true, NOW(), NOW()),
('Character Cosplay', 'کازمپلی شخصیت', 'Realistic portrayals of fictional characters from anime, games, and media', '#EF4444', NULL, 2, true, NOW(), NOW()),
('Absurd Humor', 'طنن ابسورد', 'Whimsical and humorous scenarios featuring unexpected character combinations and situations', '#F59E0B', NULL, 3, true, NOW(), NOW()),
('Anime', 'انیمه', 'Artwork created in various anime and manga styles from different eras', '#EC4899', NULL, 4, true, NOW(), NOW()),
('Crossover Mashup', 'ادغام فرنچایز', 'Creative combinations of characters and elements from different franchises', '#8B5CF6', NULL, 5, true, NOW(), NOW()),
('Character in Real Life', 'شخصیت در زندگی واقعی', 'Fictional characters placed in realistic, everyday situations and environments', '#06B6D4', NULL, 6, true, NOW(), NOW()),
('Cute Selfie', 'سلفی بامزه', 'Charming self-portrait style images with playful and endearing qualities', '#F97316', NULL, 7, true, NOW(), NOW()),
('Architectural Concept', 'مفهوم معماری', 'Imaginative building designs and urban landscape concepts', '#64748B', NULL, 8, true, NOW(), NOW()),
('Political Portrait', 'پرتره سیاسی', 'Satirical or serious depictions of political figures and scenarios', '#475569', NULL, 9, true, NOW(), NOW()),
('Album Art', 'طرح آلبوم', 'Artwork designed for music albums and promotional materials', '#10B981', NULL, 10, true, NOW(), NOW()),
('Minimalist Photography', 'عکاسی مینیمال', 'Clean, simple photographic compositions with emphasis on negative space', '#6B7280', NULL, 11, true, NOW(), NOW()),
('Sci-Fi Art', 'هنر علمی تخیلی', 'Futuristic and speculative fiction artwork with technological themes', '#6366F1', NULL, 12, true, NOW(), NOW()),
('Animal Portrait', 'پرتره حیوانات', 'Artistic depictions of animals in various styles and settings', '#84CC16', NULL, 13, true, NOW(), NOW()),
('Movie Poster', 'پوستر فیلم', 'Promotional artwork designed in the style of movie posters', '#DC2626', NULL, 14, true, NOW(), NOW()),
('Artistic Technique', 'تکنیک هنری', 'Artwork showcasing specific artistic styles, methods, or visual effects', '#7C3AED', NULL, 15, true, NOW(), NOW()),
('Wallpaper', 'والپیپر', 'Artwork designed specifically for use as desktop or mobile backgrounds', '#059669', NULL, 16, true, NOW(), NOW()),
('Cartoon Realism', 'رئالیسم کارتونی', 'Realistic interpretations of traditionally cartoon characters', '#D97706', NULL, 17, true, NOW(), NOW()),
('Wildlife Photography', 'عکاسی حیات وحش', 'Realistic depictions of animals in their natural habitats', '#65A30D', NULL, 18, true, NOW(), NOW());


INSERT INTO `ai_models` (`name`, `vendor`, `model_identifier`, `description`, `version`, `is_active`) VALUES
('GPT-4 Turbo', 'OpenAI', 'gpt-4-turbo-preview', 'OpenAI\'s most powerful model with 128K context window and knowledge up to April 2023', 'turbo-preview', 1),
('GPT-4', 'OpenAI', 'gpt-4', 'OpenAI\'s advanced multimodal model with strong reasoning capabilities', '4', 1),
('GPT-3.5 Turbo', 'OpenAI', 'gpt-3.5-turbo', 'Fast and cost-effective model for everyday tasks', '3.5-turbo', 1),
('Claude 3 Opus', 'Anthropic', 'claude-3-opus-20240229', 'Anthropic\'s most intelligent model for highly complex tasks', '20240229', 1),
('Claude 3 Sonnet', 'Anthropic', 'claude-3-sonnet-20240229', 'Anthropic\'s balanced model between intelligence and speed', '20240229', 1),
('Claude 3 Haiku', 'Anthropic', 'claude-3-haiku-20240307', 'Anthropic\'s fastest and most compact model for simple tasks', '20240307', 1),
('Gemini 1.0 Pro', 'Google', 'gemini-pro', 'Google\'s advanced multimodal model for general purposes', '1.0', 1),
('Gemini 1.5 Pro', 'Google', 'gemini-1.5-pro', 'Google\'s latest model with million-token context window', '1.5', 1),
('Llama 3', 'Meta', 'llama-3-70b', 'Meta\'s open-source large language model with 70B parameters', '3-70b', 1),
('Mixtral 8x7B', 'Mistral AI', 'mixtral-8x7b', 'High-quality sparse mixture of experts model with 8x7B parameters', '8x7b', 1),
('DALL-E 3', 'OpenAI', 'dall-e-3', 'OpenAI\'s most advanced image generation model', '3', 1),
('Stable Diffusion XL', 'Stability AI', 'stable-diffusion-xl', 'Open-source image generation model with high-quality outputs', 'XL', 1),
('Midjourney v6', 'Midjourney', 'midjourney-v6', 'Advanced AI image generation model with photorealistic capabilities', 'v6', 1),
('Whisper Large', 'OpenAI', 'whisper-large', 'OpenAI\'s speech recognition and translation model', 'large', 1),
('GPT-4 Vision', 'OpenAI', 'gpt-4-vision-preview', 'Multimodal model that can understand images and text', 'vision-preview', 1),
('Jurassic-2 Ultra', 'AI21 Labs', 'j2-ultra', 'AI21 Studio\'s most capable model for complex reasoning', '2-ultra', 1),
('Command R+', 'Cohere', 'command-r-plus', 'Cohere\'s advanced model for enterprise applications', 'r-plus', 1),
('Claude Instant', 'Anthropic', 'claude-instant-1.2', 'Anthropic\'s faster and more affordable model', '1.2', 0),
('GPT-3', 'OpenAI', 'gpt-3', 'Legacy OpenAI model (deprecated)', '3', 0),
('Codex', 'OpenAI', 'code-davinci-002', 'OpenAI\'s code generation model (deprecated)', 'davinci-002', 0);

INSERT INTO `user_prompts` (`user_id`, `category_id`, `title`, `description`, `content`, `ai_model_ids`, `is_favorite`, `created_at`) VALUES
(1, 1, 'ایمیل بازاریابی حرفه‌ای', 'قالب ایمیل برای جذب مشتریان جدید', 'یک ایمیل بازاریابی حرفه‌ای بنویس که شامل معرفی محصول، مزایای آن و دعوت به اقدام واضح باشد. ایمیل باید جذاب، مختصر و مؤثر باشد.', '1,2,3', 1, '2024-01-15 10:30:00'),
(1, 1, 'پست اینستاگرام محصول', 'قالب پست برای معرفی محصول در اینستاگرام', 'یک پست اینستاگرام جذاب برای محصول جدید ما ایجاد کن. شامل توضیحات کوتاه، هشتگ‌های مرتبط و دعوت به تعامل.', '1,2,3', 0, '2024-01-16 14:20:00'),
(1, 3, 'کد پیاده‌سازی API', 'ساختار پایه برای API endpoint', 'یک endpoint API RESTful با Node.js و Express ایجاد کن که شامل validation، error handling و documentation باشد.', '3,9,10', 1, '2024-01-17 09:45:00'),
(1, 4, 'تحلیل داده فروش', 'آنالیز داده‌های فروش فصلی', 'یک گزارش تحلیل داده برای فروش سه ماهه ایجاد کن. شامل نمودارها، insights و پیشنهادات بهبود.', '4,5,6', 0, '2024-01-18 16:10:00'),
(1, 5, 'داستان خلاقانه کوتاه', 'داستان کوتاه با موضوع فناوری', 'یک داستان کوتاه 500 کلمه‌ای درباره تأثیر هوش مصنوعی بر زندگی انسان بنویس.', '1,2,5', 1, '2024-01-19 11:30:00'),
(1, 6, 'پاسخ پشتیبانی مشتری', 'قالب پاسخ به شکایت مشتری', 'یک پاسخ حرفه‌ای و همدلانه به شکایت مشتری بنویس که شامل عذرخواهی، راه‌حل و پیگیری باشد.', '1,2,7', 0, '2024-01-20 13:15:00'),
(1, 2, 'اسکریپت ویدیوی آموزشی', 'اسکریپت برای ویدیوی آموزشی 5 دقیقه‌ای', 'اسکریپت کامل برای یک ویدیوی آموزشی درباره مفاهیم پایه برنامه‌نویسی ایجاد کن.', '2,3,8', 1, '2024-01-21 15:40:00'),
(1, 1, 'بهینه‌سازی سئو', 'چک‌لیست سئو برای محتوای وب', 'یک چک‌لیست جامع برای بهینه‌سازی سئو محتوای وب ایجاد کن که شامل meta tags، keywords و ساختار محتوا باشد.', '1,4,6', 0, '2024-01-22 08:50:00'),
(1, 5, 'نام‌گذاری محصول جدید', 'ایده‌های نام برای محصول tech جدید', '10 ایده خلاقانه برای نام‌گذاری یک محصول نرم‌افزاری جدید ایجاد کن.', '5,8,9', 1, '2024-01-23 12:25:00'),
(1, 4, 'گزارش مالی سه‌ماهه', 'قالب گزارش مالی حرفه‌ای', 'یک گزارش مالی سه‌ماهه با ساختار استاندارد ایجاد کن که شامل درآمد، هزینه‌ها و تحلیل روند باشد.', '4,6,7', 0, '2024-01-24 17:05:00'),
(1, 2, 'محتوای وبلاگ سلامت', 'مقاله درباره تغذیه سالم', 'یک مقاله 1000 کلمه‌ای درباره اهمیت تغذیه سالم و تأثیر آن بر سلامت روان بنویس.', '1,2,8', 1, '2024-01-25 10:15:00'),
(1, 3, 'کد authentication', 'سیستم احراز هویت امن', 'یک سیستم احراز هویت با Node.js ایجاد کن که شامل register، login، JWT و password hashing باشد.', '3,9,10', 1, '2024-01-26 14:30:00'),
(1, 1, 'استراتژی شبکه‌های اجتماعی', 'برنامه محتوای ماهانه', 'یک استراتژی محتوای ماهانه برای شبکه‌های اجتماعی ایجاد کن که شامل calendar، content ideas و engagement tactics باشد.', '1,2,4', 0, '2024-01-27 09:20:00'),
(1, 2, 'رزومه حرفه‌ای', 'قالب رزومه برای توسعه‌دهنده', 'یک رزومه حرفه‌ای برای توسعه‌دهنده full-stack ایجاد کن که شامل skills، experience و projects باشد.', '1,2,3', 1, '2024-01-28 16:45:00'),
(1, 4, 'برنامه کسب‌وکار', 'طرح کسب‌وکار استارتاپ', 'یک طرح کسب‌وکار کامل برای استارتاپ tech ایجاد کن که شامل market analysis، financial projections و growth strategy باشد.', '1,4,6', 0, '2024-01-29 11:10:00');

INSERT INTO `tags` (`name`) VALUES
('بازاریابی'),
('سئو'),
('شبکه‌های‌اجتماعی'),
('ایمیل'),
('تولید‌محتو'),
('بلاگ‌نویسی'),
('کپی‌رایتینگ'),
('برنامه‌نویسی'),
('جاوااسکریپت'),
('پایتون'),
('نودجی‌اس'),
('ای‌پی‌آی'),
('توسعه‌وب'),
('تحلیل‌داده'),
('آنالیتیکس'),
('گزارش‌دهی'),
('نمایش‌داده'),
('خلاقیت'),
('ایده‌پردازی'),
('طوفان‌فکری'),
('داستان‌سرایی'),
('طراحی'),
('پشتیبانی‌مشتری'),
('سرویس‌دهی'),
('سوالات‌متداول'),
('عیب‌یابی'),
('کسب‌وکار'),
('استراتژی'),
('برنامه‌ریزی'),
('بهره‌وری'),
('اتوماسیون'),
('هوش‌مصنوعی'),
('چت‌جی‌پی‌تی'),
('میجورنی'),
('تولید‌تصویر'),
('ویدیو'),
('فیلمنامه‌نویسی'),
('آموزش'),
('آموزشی'),
('یادگیری'),
('تجارت‌الکترونیک'),
('فروش'),
('تبدیل'),
('بهینه‌سازی‌سئو'),
('کلمات‌کلیدی'),
('بازاریابی‌شبکه‌اجتماعی'),
('اینستاگرام'),
('لینکدین'),
('توییتر'),
('فیسبوک'),
('یوتیوب'),
('محتوای‌ویدیویی'),
('صدا'),
('پادکست'),
('گویندگی'),
('ترجمه'),
('چند‌زبانه'),
('فنی'),
('مستندسازی'),
('بازبینی‌کد'),
('اشکال‌زدایی'),
('تست‌نرم‌افزار'),
('تجربه‌کاربری'),
('طراحی‌رابط‌کاربری'),
('اپلیکیشن‌موبایل'),
('طراحی‌واکنش‌گرا'),
('ابر'),
('دوواپس'),
('امنیت'),
('احراز‌هویت'),
('پایگاه‌داده'),
('ذخیره‌سازی'),
('هوش‌تجاری'),
('یادگیری‌ماشین'),
('داده‌کاوی'),
('بلاک‌چین'),
('ارز‌دیجیتال'),
('متاورس'),
('واقعیت‌مجازی'),
('واقعیت‌افزوده'),
('رباتیک'),
('اینترنت‌اشیا'),
('پردازش‌زبان‌طبیعی'),
('بینایی‌کامپیوتر'),
('پردازش‌تصویر'),
('صوت'),
('تشخیص‌صدا'),
('تبدیل‌متن‌به‌صدا'),
('تبدیل‌صدا‌به‌متن'),
('خلاصه‌سازی'),
('ترجمه‌ماشینی'),
('تولید‌محتوا'),
('ویرایش‌تصویر'),
('ویرایش‌ویدیو'),
('گرافیک'),
('انیمیشن'),
('موشن‌گرافیک'),
('طراحی‌لوگو'),
('برندینگ'),
('هویت‌تصویری'),
('بسته‌بندی'),
('تبلیغات'),
('کمپین‌تبلیغاتی'),
('بازاریابی‌محتوایی'),
('بازاریابی‌ایمیل'),
('بازاریابی‌موبایل'),
('بازاریابی‌ویدیویی'),
('بازاریابی‌تاثیرگذار'),
('تحلیل‌رقبا'),
('تحلیل‌بازار'),
('تحقیق‌بازار'),
('نظرسنجی'),
('آمار'),
('احتمالات'),
('هوش‌مصنوعی‌اخلاقی'),
('هوش‌مصنوعی‌قابل‌توضیح'),
('هوش‌مصنوعی‌قوی'),
('هوش‌مصنوعی‌ضعیف'),
('شبکه‌عصبی'),
('یادگیری‌عمیق'),
('یادگیری‌تقویتی'),
('پردازش‌سیگنال'),
('پردازش‌ویدیو'),
('فشرده‌سازی'),
('رمزنگاری'),
('امنیت‌سایبری'),
('حملات‌سایبری'),
('دفاع‌سایبری'),
('قانون‌هوش‌مصنوعی'),
('اخلاق‌هوش‌مصنوعی'),
('توسعه‌پایدار'),
('فناوری‌سبز'),
('انرژی‌های‌تجدیدپذیر'),
('کشاورزی‌هوشمند'),
('شهر‌هوشمند'),
('حمل‌ونقل‌هوشمند'),
('سلامت‌دیجیتال'),
('پزشکی‌از‌راه‌دور'),
('تشخیص‌بیماری'),
('پیش‌بینی‌بیماری'),
('داروسازی‌دیجیتال'),
('ژنتیک'),
('بیوانفورماتیک'),
('نانوفناوری'),
('فناوری‌کوانتومی'),
('محاسبات‌کوانتومی'),
('رمزنگاری‌کوانتومی'),
('سفر‌در‌زمان'),
('هوش‌فرازمینی'),
('اکتشاف‌فضا'),
('نجوم'),
('فیزیک‌نظری'),
('ریاضیات'),
('آمار'),
('محاسبات'),
('الگوریتم'),
('ساختمان‌داده'),
('پایگاه‌داده‌نویسی'),
('هک‌اخلاقی'),
('پنتست'),
('تحلیل‌بدافزار'),
('امنیت‌شبکه'),
('فایروال'),
('وی‌پی‌ان'),
('ابری‌امن'),
('ذخیره‌سازی‌ابری'),
('پردازش‌ابری'),
('رایانش‌ابری'),
('رایانش‌لبه'),
('اینترنت‌اشیاء'),
('خانه‌هوشمند'),
('شهر‌هوشمند'),
('صنعت‌۴.۰'),
('اتوماسیون‌صنعتی'),
('رباتیک‌صنعتی'),
('پرینت‌سه‌بعدی'),
('طراحی‌سه‌بعدی'),
('مدل‌سازی‌سه‌بعدی'),
('واقعیت‌مجازی'),
('واقعیت‌افزوده'),
('واقعیت‌ترکیبی'),
('بازی‌سازی'),
('توسعه‌بازی'),
('گرافیک‌بازی'),
('موتور‌بازی'),
('یونیتی'),
('آنریل'),
('کرای‌انجین'),
('شبیه‌سازی'),
('مدل‌سازی'),
('پیش‌بینی'),
('بهینه‌سازی'),
('جست‌وجو'),
('الگوریتم‌ژنتیک'),
('ازدحام‌ذرات'),
('کلونی‌مورچه‌ها'),
('شبکه‌عصبی‌مصنوعی'),
('یادگیری‌عمیق'),
('بینایی‌ماشین'),
('پردازش‌زبان'),
('تولید‌زبان'),
('ترجمه‌ماشین'),
('چت‌بات'),
('دستیار‌مجازی'),
('سیری'),
('الکسا'),
('گوگل‌اسیستنت'),
('دستیار‌هوشمند'),
('کاربری‌صوتی'),
('کنترل‌صوتی'),
('تشخیص‌چهره'),
('بیومتریک'),
('امنیت‌بیومتریک'),
('احراز‌هویت‌چهره'),
('تشخیص‌حالت‌چهره'),
('تشخیص‌عواطف'),
('پردازش‌عواطف'),
('هوش‌عاطفی'),
('ربات‌اجتماعی'),
('همراه‌هوشمند'),
('پرستار‌ربات'),
('معلم‌ربات'),
('مشاور‌ربات'),
('درمان‌ربات'),
('جراحی‌ربات'),
('پزشکی‌رباتیک'),
('سلامت‌رباتیک'),
('بازتوانی‌رباتیک'),
('پروتز‌هوشمند'),
('اسکلت‌رباتیک'),
('نانوروبات'),
('میکروروبات'),
('ربات‌هوایی'),
('درون‌پاد'),
('کوادکوپتر'),
('ربات‌زمینی'),
('ربات‌تحرک'),
('ناوبری‌ربات'),
('بینایی‌ربات'),
('پردازش‌تصویر‌ربات'),
('کنترل‌ربات'),
('برنامه‌نویسی‌ربات'),
('شبیه‌سازی‌ربات'),
('یادگیری‌ربات'),
('یادگیری‌تقویتی‌ربات'),
('همکاری‌ربات'),
('ربات‌همکار'),
('اتوماسیون‌رباتیک'),
('خط‌مونتاژ‌رباتیک'),
('تولید‌رباتیک'),
('صنعت‌رباتیک'),
('کشاورزی‌رباتیک'),
('ربات‌کشاورز'),
('آبیاری‌هوشمند'),
('نظارت‌بر‌محصول'),
('برداشت‌رباتیک'),
('هرس‌رباتیک'),
('ماهیگیری‌رباتیک'),
('شکار‌رباتیک'),
('جست‌وجو‌و‌نجات'),
('ربات‌نجات'),
('اکتشاف‌زیرآب'),
('ربات‌زیردریایی'),
('اکتشاف‌فضا'),
('ربات‌فضایی'),
('مریخ‌نورد'),
('ماه‌نورد'),
('سیارک‌نورد'),
('اکتشاف‌اعماق'),
('ربات‌عمق'),
('معدن‌کاری‌رباتیک'),
('حفاری‌رباتیک'),
('ساخت‌وساز‌رباتیک'),
('بنایی‌رباتیک'),
('جاده‌سازی‌رباتیک'),
('تعمیرات‌رباتیک'),
('نگهداری‌رباتیک'),
('تمیزکاری‌رباتیک'),
('ربات‌نظافتچی'),
('ربات‌پذیرایی'),
('ربات‌آشپز'),
('پخت‌رباتیک'),
('سرویس‌رباتیک'),
('هتل‌رباتیک'),
('رستوران‌رباتیک'),
('خرده‌فروشی‌رباتیک'),
('انبارداری‌رباتیک'),
('جابه‌جایی‌رباتیک'),
('بسته‌بندی‌رباتیک'),
('تحویل‌رباتیک'),
('پست‌رباتیک'),
('تحویل‌با‌درون'),
('تحویل‌خودکار'),
('خودرو‌خودران'),
('رانندگی‌خودکار'),
('ناوبری‌خودکار'),
('هوانوردی‌خودکار'),
('هواپیما‌خودران'),
('کشتی‌خودران'),
('قطار‌خودران'),
('اتوبوس‌خودران'),
('تاکسی‌خودران'),
('تحویل‌خودرو'),
('پارکینگ‌خودکار'),
('ترافیک‌هوشمند'),
('کنترل‌ترافیک'),
('شبکه‌هوشمند'),
('برق‌هوشمند'),
('آب‌هوشمند'),
('گاز‌هوشمند'),
('انرژی‌هوشمند'),
('مدیریت‌انرژی'),
('بهینه‌سازی‌انرژی'),
('صرفه‌جویی‌انرژی'),
('انرژی‌های‌تجدیدپذیر'),
('خورشیدی'),
('بادی'),
('آبی'),
('زمین‌گرمایی'),
('بیومس'),
('هیدروژن'),
('پیل‌سوختی'),
('ذخیره‌سازی‌انرژی'),
('باتری'),
('ابرخازن'),
('flywheel'),
('ذخیره‌سازی‌هیدروژن'),
('ذخیره‌سازی‌حرارتی'),
('شبکه‌هوشمند‌برق'),
('متر‌هوشمند'),
('خانه‌هوشمند'),
('ساختمان‌هوشمند'),
('شهر‌هوشمند'),
('حمل‌ونقل‌هوشمند'),
('سلامت‌هوشمند'),
('آموزش‌هوشمند'),
('کشاورزی‌هوشمند'),
('صنعت‌هوشمند'),
('خرده‌فروشی‌هوشمند'),
('بانکداری‌هوشمند'),
('بیمه‌هوشمند'),
('قضایی‌هوشمند'),
('دولت‌هوشمند'),
('خدمات‌هوشمند'),
('شهروند‌هوشمند'),
('زندگی‌هوشمند'),
('محیط‌زیست‌هوشمند'),
('نظارت‌هوشمند'),
('کنترل‌هوشمند'),
('بهینه‌سازی‌هوشمند'),
('تصمیم‌گیری‌هوشمند'),
('پیش‌بینی‌هوشمند'),
('تحلیل‌هوشمند'),
('یادگیری‌هوشمند'),
('تکامل‌هوشمند'),
('هوش‌جمعی'),
('ازدحام‌هوشمند'),
('الگوریتم‌هوشمند'),
('محاسبه‌هوشمند'),
('پردازش‌هوشمند'),
('ذخیره‌سازی‌هوشمند'),
('انتقال‌هوشمند'),
('ارتباط‌هوشمند'),
('شبکه‌هوشمند'),
('ابر‌هوشمند'),
('لبه‌هوشمند'),
('دستگاه‌هوشمند'),
('وسیله‌هوشمند'),
('ابزار‌هوشمند'),
('سیستم‌هوشمند'),
('پلتفرم‌هوشمند'),
('نرم‌افزار‌هوشمند'),
('سخت‌افزار‌هوشمند'),
('تراشه‌هوشمند'),
('پردازنده‌هوشمند'),
('حافظه‌هوشمند'),
('ذخیره‌سازی‌هوشمند'),
('نمایش‌هوشمند'),
('ورودی‌هوشمند'),
('خروجی‌هوشمند'),
('کنترل‌هوشمند'),
('فرمان‌هوشمند'),
('ناوبری‌هوشمند'),
('هدایت‌هوشمند'),
('راهبری‌هوشمند'),
('مدیریت‌هوشمند'),
('نظارت‌هوشمند'),
('کنترل‌هوشمند'),
('بهینه‌سازی‌هوشمند'),
('تصمیم‌گیری‌هوشمند'),
('پیش‌بینی‌هوشمند'),
('تحلیل‌هوشمند'),
('یادگیری‌هوشمند'),
('تکامل‌هوشمند'),
('هوش‌جمعی'),
('ازدحام‌هوشمند'),
('الگوریتم‌هوشمند'),
('محاسبه‌هوشمند'),
('پردازش‌هوشمند'),
('ذخیره‌سازی‌هوشمند'),
('انتقال‌هوشمند'),
('ارتباط‌هوشمند'),
('شبکه‌هوشمند'),
('ابر‌هوشمند'),
('لبه‌هوشمند'),
('دستگاه‌هوشمند'),
('وسیله‌هوشمند'),
('ابزار‌هوشمند'),
('سیستم‌هوشمند'),
('پلتفرم‌هوشمند'),
('نرم‌افزار‌هوشمند'),
('سخت‌افزار‌هوشمند'),
('تراشه‌هوشمند'),
('پردازنده‌هوشمند'),
('حافظه‌هوشمند'),
('ذخیره‌سازی‌هوشمند'),
('نمایش‌هوشمند'),
('ورودی‌هوشمند'),
('خروجی‌هوشمند'),
('کنترل‌هوشمند'),
('فرمان‌هوشمند'),
('ناوبری‌هوشمند'),
('هدایت‌هوشمند'),
('راهبری‌هوشمند'),
('مدیریت‌هوشمند'),
('نظارت‌هوشمند'),
('کنترل‌هوشمند'),
('بهینه‌سازی‌هوشمند'),
('تصمیم‌گیری‌هوشمند'),
('پیش‌بینی‌هوشمند'),
('تحلیل‌هوشمند'),
('یادگیری‌هوشمند'),
('تکامل‌هوشمند'),
('هوش‌جمعی'),
('ازدحام‌هوشمند'),
('الگوریتم‌هوشمند'),
('محاسبه‌هوشمند'),
('پردازش‌هوشمند'),
('ذخیره‌سازی‌هوشمند'),
('انتقال‌هوشمند'),
('ارتباط‌هوشمند'),
('شبکه‌هوشمند'),
('ابر‌هوشمند'),
('لبه‌هوشمند'),
('دستگاه‌هوشمند'),
('وسیله‌هوشمند'),
('ابزار‌هوشمند'),
('سیستم‌هوشمند'),
('پلتفرم‌هوشمند'),
('نرم‌افزار‌هوشمند'),
('سخت‌افزار‌هوشمند'),
('تراشه‌هوشمند'),
('پردازنده‌هوشمند'),
('حافظه‌هوشمند'),
('ذخیره‌سازی‌هوشمند'),
('نمایش‌هوشمند'),
('ورودی‌هوشمند'),
('خروجی‌هوشمند'),
('کنترل‌هوشمند'),
('فرمان‌هوشمند'),
('ناوبری‌هوشمند'),
('هدایت‌هوشمند'),
('راهبری‌هوشمند'),
('مدیریت‌هوشمند'),
('نظارت‌هوشمند'),
('کنترل‌هوشمند'),
('بهینه‌سازی‌هوشمند'),
('تصمیم‌گیری‌هوشمند'),
('پیش‌بینی‌هوشمند'),
('تحلیل‌هوشمند'),
('یادگیری‌هوشمند'),
('تکامل‌هوشمند'),
('هوش‌جمعی'),
('ازدحام‌هوشمند'),
('الگوریتم‌هوشمند'),
('محاسبه‌هوشمند'),
('پردازش‌هوشمند'),
('ذخیره‌سازی‌هوشمند'),
('انتقال‌هوشمند'),
('ارتباط‌هوشمند'),
('شبکه‌هوشمند'),
('ابر‌هوشمند'),
('لبه‌هوشمند');

INSERT INTO prompt_templates (title, description, content, ai_model_id, category_id, user_id, total_likes, total_views, is_public, metadata, created_at, updated_at) VALUES
('Playful Bubble Gum Portrait', 'A cinematic urban portrait of a girl blowing bubble gum playfully', 'She`s blowing bubble gum playfully toward the camera. Slight visual noise and grain texture, subtle distortion from the lens, cheeky expression, urban residential vibe, cinematic framing, high contrast shadows', 1, 1, 1, 0, 0, 1, '{"original_id": "d2994f02-9175-4f1a-9e86-527d570a2bb1", "style": "cinematic", "mood": "playful", "environment": "urban"}', NOW(), NOW()),
('Realistic Misty Cosplay', 'Photorealistic Misty from Pokemon in a dark aesthetic setting', 'A real life photo photo of misty from pkemon. She is smiling (head sligtly tilt, holding a half white half red baseball. The other hand is making a peace sign.\nThere is two star fishes beside her. dark aesthetic.', 1, 2, 1, 0, 0, 1, '{"original_id": "8026208b-5d3f-45d8-a9cd-08d35bea0f0d", "character": "Misty", "franchise": "Pokemon", "style": "photorealistic"}', NOW(), NOW()),
('Urban Bubble Gum Scene', 'Cinematic urban portrait with playful bubble gum moment', 'She`s blowing bubble gum playfully toward the camera. Slight visual noise and grain texture, subtle distortion from the lens, cheeky expression, urban residential vibe, cinematic framing, high contrast shadows', 1, 1, 1, 0, 0, 1, '{"original_id": "0abe3caa-8b60-48a0-969d-6902c2c6168f", "style": "cinematic", "mood": "playful", "environment": "urban"}', NOW(), NOW()),
('Panda Driving Sports Car', 'Absurd scene of a panda driving erratically at night', 'Footage of a panda driving a sports car erratically on a highway at night (live action style)', 1, 3, 1, 0, 0, 1, '{"original_id": "84b566e6-5227-4dce-a832-dbff3efd2127", "absurd": true, "animals": "panda", "action": "driving"}', NOW(), NOW()),
('Anime College Girl Selfie', 'Close-up anime style selfie of Japanese college woman', 'anime, close up selfie-shots of japanese woman in college', 1, 4, 1, 0, 0, 1, '{"original_id": "1ef84da0-a4e5-4346-890d-377a24dec728", "style": "anime", "type": "selfie", "subject": "college girl"}', NOW(), NOW()),
('90s Anime Pilot Girl', 'Moody lighting portrait of a brunette pilot in 90s anime style', 'A beautiful brunette pilot girl, beautiful, moody lighting, 90s anime minimal masterpiexce', 1, 4, 1, 0, 0, 1, '{"original_id": "5f810a1e-605d-4116-9c26-2b37642e3c16", "era": "90s", "style": "anime", "occupation": "pilot"}', NOW(), NOW()),
('90s Classroom Crossover', 'Minecraft Steve, Yoshi, Sonic, Trump and Harry Potter in classroom', 'A 90''s classroom with the following characters sitting on desks blocky Minecraft Steve, Yoshi, Sonic, Donald Trump, and Harry Potter.', 1, 5, 1, 0, 0, 1, '{"original_id": "26458208-3252-44a2-867a-968f53496e0f", "crossover": true, "characters": ["Minecraft Steve", "Yoshi", "Sonic", "Trump", "Harry Potter"]}', NOW(), NOW()),
('Kirby Target Employee ID', 'Awkward employee photo of Kirby as Target team member', 'Awkward employee ID badge photo of Kirby as new Target team member, too close to camera, red vest barely fitting his round body, name tag just says "KIRBY." Photo of Kirby wearing the badge.', 1, 6, 1, 0, 0, 1, '{"original_id": "25f8a7d1-5dcc-44df-ae8b-655efd9de2d9", "character": "Kirby", "situation": "workplace", "mood": "awkward"}', NOW(), NOW()),
('Gothic Rooftop Contemplation', 'Cinematic shot of woman on Zurich rooftop with gothic aesthetic', 'Shot with ARRI ALEXA Mini LF, medium shot, low-angle perspective. A young woman with straight black hair and blunt bangs sits quietly on the edge of a rooftop, overlooking the cloudy cityscape of Zurich. She wears a sheer black lace dress, black transparent tights, and dark lipstick, creating a striking contrast against the muted, overcast sky. Her posture is calm and contemplative, with her gaze lost in the distance. The cool tones of the cloudy daylight enhance the gothic and delicate aesthetic of her look, while the urban background adds depth to the scene.', 1, 1, 1, 0, 0, 1, '{"original_id": "83042c0d-90f7-4e8d-a310-280d7f9a0fb4", "style": "cinematic", "aesthetic": "gothic", "location": "Zurich"}', NOW(), NOW()),
('80s Anime Elf Ballroom', 'Worried elf woman in dragon pattern ballgown, 80s anime style', 'beautiful elf woman with very long, wavy copper orange hair. she''s wearing a beautiful ballgown with dragon patterns on it. she''s standing in the doorway to a ballroom where people are dancing. she''s looking over her shoulder. her facial expression is worried. she has freckles. very beautiful elf woman with very long copper red hair. her eyes are a grayish blue.. 80s anime style', 1, 4, 1, 0, 0, 1, '{"original_id": "f068b476-a4c7-4a22-a6c0-01a105c1d098", "era": "80s", "style": "anime", "fantasy": "elf"}', NOW(), NOW()),
('Patrick Star Fancy Date', 'Grunge analog photo of Patrick Star on a date in restaurant', 'A grungy, analog 11 photo of Patrick Star from spongebob in on a date with the POV in a fancy restaurant. he is holding the POV''s hand and smirking. The photo was taken with flash, unedited, with a gritty, raw look', 1, 6, 1, 0, 0, 1, '{"original_id": "bb7cc569-d8ce-462e-9e24-052e0c4164d2", "character": "Patrick Star", "style": "grunge", "situation": "date"}', NOW(), NOW()),
('White Haired Girl with Cat', 'Cute selfie of white-haired woman with orange cat', 'A 22-year-old woman with long white hair selfie photo with an orange cat. silly and cute', 1, 7, 1, 0, 0, 1, '{"original_id": "97f0a6ce-891b-4c12-99ac-365180967572", "subject": "woman", "pet": "cat", "mood": "cute"}', NOW(), NOW()),
('McDonald''s Hamburger Building', 'Realistic giant hamburger-shaped McDonald''s store in Shanghai', 'A realistic giant hamburger-shaped multi-level pop-up store on a busy city street, branded with the McDonald''s logo, each layer of the burger is a floor with windows, McDonald''s workers visible preparing burgers inside, lively urban atmosphere, realistic lighting, Shanghai skyline in the background, photorealistic tilt shift photo', 1, 8, 1, 0, 0, 1, '{"original_id": "bfde50df-9300-4cd3-9aec-5a382b617674", "architecture": "creative", "brand": "McDonald''s", "location": "Shanghai"}', NOW(), NOW()),
('Fascist President Portrait', 'Portrait of a fascist president', 'the fascist president', 1, 9, 2, 0, 0, 1, '{"original_id": "4b9aefa1-5f91-44cf-9060-607ca0f2e226", "political": true, "style": "portrait"}', NOW(), NOW()),
('80s Anime Protagonist', '80s anime character lighting cigarette in front of Tower Records', '80s anime, protagonist lighting a cigarettein front of tower records', 1, 4, 1, 0, 0, 1, '{"original_id": "87a6d493-0390-424a-a2c2-f959d7445e2f", "era": "80s", "style": "anime", "action": "smoking"}', NOW(), NOW()),
('Nintendo Kendrick Lamar Album', 'Kendrick Lamar style album art featuring Nintendo characters', 'kendrick lamar style album art but its nintendo characters', 1, 10, 3, 0, 0, 1, '{"original_id": "e180853a-9ddc-4b28-86e2-00d0c4763540", "music": "album art", "style": "Kendrick Lamar", "characters": "Nintendo"}', NOW(), NOW()),
('Minimalist Japan Photography', 'Minimalist blissful Japanese scene shot on Leica', 'minimalist bliss. japan. shot on leica.', 1, 11, 1, 0, 0, 1, '{"original_id": "bfffdce9-d4d0-406f-9fb0-5fce4b71972c", "style": "minimalist", "location": "Japan", "camera": "Leica"}', NOW(), NOW()),
('Gritty Elsa Selfie Alley', 'Grainy iPhone photo of Elsa taking moody selfie in abandoned alley', 'Grainy iPhone 6 flash photo of Elsa from Frozen taking a moody selfie in a dark, abandoned alleyway. She stands against a crumbling, graffiti-sprayed brick wall, the fluorescent paint peeling and flaking under years of neglect. Elsa''s platinum-blonde hair is loosely tied back, with two soft strands falling across her pale, freckled face. She wears a glittering but slightly torn silver-blue gown, its shimmer dulled under layers of city grime. A thin silver chain necklace glints under the harsh flash.\n\nElsa holds a glass of wine in one hand. Her other hand lifts the phone for the shot, and the flash bounces sharply off her pale skin, bleaching her features and casting deep shadows into the corners of the alley. A cigarette butt lies crushed by her silver heel at the bottom of the frame.\n\nHer expression is sharp, melancholic, and defiantly amused — a fallen queen savoring a moment of ruined beauty. The ground is cracked concrete littered with shattered glass. The grainy flash photo captures a raw, analog, unfiltered snapshot — rich with a 90s VHS nostalgia, grungy texture, and the heavy, timeless weight of forgotten dreams.', 1, 6, 1, 0, 0, 1, '{"original_id": "2b1187b1-25f1-4d40-90ca-acd90b18c2a8", "character": "Elsa", "style": "grunge", "mood": "melancholic"}', NOW(), NOW()),
('Wendy''s Waitress Casual Photo', 'Ordinary iPhone photo of Chinese waitress at Wendy''s', 'An extremely ordinary iPhone photo taken from a low angle, with no clear subject or composition, looking like a careless snapshot. The overall effect is very mediocre, as if it were an accidental photo.\n\nThis is a 22-year-old Chinese girl with striking black hair styled in a beautiful ponytail that moves slightly as she moves, tied with a bright blue ribbon. Her fair skin is dotted with light freckles on her cheeks, adding to her fresh, youthful charm. Her smile is gentle and sincere, lighting up her face with a quiet warmth. Her eyes are round and expressive, sparkling with a hint of mischief and kindness. She wears a blue-and-white gingham checkered dress with short, puffy sleeves and a low square neckline, paired with a white apron that has a lace trim tied over it. She accessorizes with red-and-white striped arm warmers and matching thigh-high stockings, adding a playful, whimsical touch to her look. Her overall presence is vibrant, yet naturally graceful, nostalgic yet lively.\n\nShe sits on top of a red table at an outdoor seating area of a fast-food restaurant, with the Wendy''s sign visible beside the building. She leans slightly, knees bent, hugging her legs. She is barefoot, with pale blue-painted nails resting on the bench seat. A fast food bag sits next to her on the table.', 1, 7, 1, 0, 0, 1, '{"original_id": "a8ba0233-6957-4324-b722-0602761dc3ad", "style": "casual", "location": "Wendy''s", "mood": "playful"}', NOW(), NOW()),
('Sci-Fi Mammoth Painting', 'Mammoth with sci-fi twist in oil painting style', 'Mammoth with science fiction twist  - oil painitng style of Bernie Wrghtson and Wally Wood', 1, 12, 4, 0, 0, 1, '{"original_id": "dce05551-326b-437e-afc1-4b9a5bca0902", "style": "oil painting", "subject": "mammoth", "genre": "sci-fi"}', NOW(), NOW()),
('Anime Girl 5 Minutes', 'Japanese anime girl enthusiastically saying "5 minutes"', 'Japanese anime-style illustration of a lively woman with short hair and straight-cut bangs. She dramatically extends her open hand forward, with an exaggerated, cheerful manga-style smile, as if enthusiastically insisting "5 minutes". Her eyes sparkle brightly with lively energy. Behind her are a bookshelf, a desk, and a clock, forming a cozy and relaxed interior scene. A cat sits quietly nearby, adding warmth and charm. The color palette is vivid and pop-inspired, with cheerful tones, but the overall mood remains calm and soothing. The composition features clean, expressive linework and soft shading, balancing vibrant energy with a gentle atmosphere.', 1, 4, 1, 0, 0, 1, '{"original_id": "3175cf0b-065b-4639-a403-c4ec8b97b138", "style": "anime", "mood": "cheerful", "action": "gesturing"}', NOW(), NOW()),
('Sailor Moon Tomb Raider Selfie', 'iPhone selfie with Sailor Moon and Tomb Raider characters', 'iPhone selfie, with no clear subject or sense of composition—just like a casual snapshot taken at random. The photo is  The main characters are Sailor Moon and Tomb Raider.', 1, 5, 5, 0, 0, 1, '{"original_id": "5d350d43-7bba-4fc3-8ae8-c8dd389658a2", "crossover": true, "characters": ["Sailor Moon", "Tomb Raider"], "style": "selfie"}', NOW(), NOW()),
('Ultra Detailed Giraffe', 'Most beautiful and detailed giraffe portrait in 64k resolution', 'The most beautiful, amazing and awe inspiring giraffe, insane detail, ultra sharp focus, 64k', 1, 13, 1, 0, 0, 1, '{"original_id": "7b334c62-d5bc-4fa4-9eaa-db2232c57fd6", "animal": "giraffe", "quality": "64k", "detail": "ultra sharp"}', NOW(), NOW()),
('Kirby Boiler Room DJ', 'Cute Kirby DJ set with bodyguards in boiler room', 'cute Kirby boiler room dj set, wearing black sunglasses, donkey kong and king dededee are his bodyguards. pappaeazzi flash photo, does not want to be photographed.. motion blur, blurry, grainy. TMZ logo in corner. crowds in the background, flashes from camera going off, g', 1, 6, 3, 0, 0, 1, '{"original_id": "519c0daf-2d0d-4440-af97-a2da7c4f6e8c", "character": "Kirby", "situation": "DJ", "style": "paparazzi"}', NOW(), NOW()),
('Sailor Saturn Cosplay Selfie', 'Realistic selfie of woman cosplaying as Sailor Saturn', 'A realistic selfie-style portrait of a woman cosplaying as Sailor Saturn, captured from the perspective of her outstretched phone. Her arm is extended toward the camera, holding the phone at a slight high angle. She wears a detailed and well-fitted version of Sailor Saturn''s violet and white sailor uniform, complete with gloves, pleated skirt, and a shimmering silver brooch on the chest bow. Her short, sleek black hair with violet tones frames her face, and she wears a silver tiara with a purple gem. Her violet contact lenses glow subtly, and she smiles softly or gives a calm, introspective expression. The Silence Glaive is visible in the background, leaned against a wall or resting nearby. The background features a casual convention hall, softly lit room, or a starry aesthetic filter overlay. Lighting is natural and flattering, with smooth skin tones and reflective detail on her costume. The composition captures a balance of realism, character fidelity, and selfie-era charm. She is focus of the frame', 1, 2, 1, 0, 0, 1, '{"original_id": "ffe2ee8d-e516-468d-9137-178d92014f6e", "cosplay": "Sailor Saturn", "style": "realistic", "type": "selfie"}', NOW(), NOW()),
('Nintendo Cinematic Poster', '2010s cinematic minimal movie poster for Nintendo characters', '2010s cinematic minimal movie poster that goes hard but its for nintendo characters', 1, 14, 3, 0, 0, 1, '{"original_id": "209fdd75-0794-48fe-b025-ca57e2d16993", "style": "cinematic", "minimal": true, "characters": "Nintendo"}', NOW(), NOW()),
('80s Anime Dark Prince', 'Dark prince character in 80s anime minimal masterpiece style', 'Dark prince, 80s anime, minimal masterpiece', 1, 4, 1, 0, 0, 1, '{"original_id": "0fd8e3dc-aa4c-418a-99c4-ec0707ad3a99", "era": "80s", "style": "anime", "character": "dark prince"}', NOW(), NOW()),
('Arthur Morgan Double Exposure', 'Double exposure artwork of Arthur Morgan with frontier landscapes', 'Double exposure, Midjourney style, merging, blending, overlay double exposure image, Double Exposure style,\nAn exceptional masterpiece by Yukisakura revealing a fantastic double exposure composition of Arthur Morgan''s silhouette harmoniously intertwined with the visually striking, rugged landscapes of the American frontier during a cold winter. Snow-covered pine forests, frosty mountain peaks, and a lone horse cutting through the trail echo outward through the fabric of his figure, adding layers of narrative and solitude. Beautiful tension builds as the stark monochrame background maintains razor-sharp contrast, drawing all focus to the richly layered double exposure. Characterized by its vibrant full-color scheme within Arthur Morgan''s silhouette and crisp, deliberate lines that trace every contour with emotional precision. (Detailed1.45). (Detailed background1.4).', 1, 15, 1, 0, 0, 1, '{"original_id": "8d500d95-4941-40fa-9d76-b2003e30f77e", "technique": "double exposure", "character": "Arthur Morgan", "style": "artistic"}', NOW(), NOW()),
('Coffee Personification Portrait', 'Handsome young man as personification of coffee in golden light', 'Canon EOS DSLR, 85mm f1.4, extremely handsome young white man in his early 20s, personification of coffee, soft wavy dark brown hair, deep espresso-colored eyes, flawless warm skin, holding a steaming ceramic coffee cup in one hand, wearing a relaxed linen shirt slightly unbuttoned, sitting by a cafe window bathed in golden morning sunlight, subtle steam rising around his face, gentle smile with a touch of mystery, cinematic lighting, romantic', 1, 1, 1, 0, 0, 1, '{"original_id": "1b2880d6-99b1-4a18-b474-3b6346fa2c71", "style": "cinematic", "concept": "personification", "subject": "coffee"}', NOW(), NOW()),
('Asuka Langley Analog Portrait', 'Analog portrait photo of Asuka Langley Soryu in lab environment', 'Analog portrait photo of Asuka Langley Soryu, Portra 400, detailed environment, inside the LAB', 1, 2, 1, 0, 0, 1, '{"original_id": "1a13e40e-5fb6-4dbe-9a99-79d53ee2b2a6", "character": "Asuka Langley", "style": "analog", "film": "Portra 400"}', NOW(), NOW()),
('90s Anime SF Onsen Poster', '1990s anime poster for Japanese style science fiction onsen', '1990s anime poster for sf japanese style onsen, blow my mind', 1, 4, 1, 0, 0, 1, '{"original_id": "e27e8cf8-a27e-41f6-a958-2702d6d3225b", "era": "90s", "style": "anime", "theme": "onsen"}', NOW(), NOW()),
('Kirby iOS Wallpaper', 'Wallpaper design featuring Kirby for iOS devices', 'kirby wallpaper for iOS', 1, 16, 1, 0, 0, 1, '{"original_id": "e4519e38-db08-4d2a-89af-df4affbc2fac", "character": "Kirby", "purpose": "wallpaper", "platform": "iOS"}', NOW(), NOW()),
('Minions Trench Coat Disguise', 'Ring doorbell video of three Minions attempting to pose as adult', 'Ring doorbell video of three Minions in trench coat attempting to pose as one adult human', 1, 3, 1, 0, 0, 1, '{"original_id": "b941d0b2-cdbe-4c80-b871-b30ed685ce2c", "characters": "Minions", "situation": "disguise", "style": "doorbell"}', NOW(), NOW()),
('Katsuhiro Otomo Style Astronaut', 'Astronaut in space designed in Katsuhiro Otomo artistic style', 'Design an astronaut in Katsuhiro Otomo style flying in dark space.', 1, 4, 1, 0, 0, 1, '{"original_id": "5ac5ef33-12d8-4180-b5c0-f8d603c9d15f", "artist": "Katsuhiro Otomo", "subject": "astronaut", "environment": "space"}', NOW(), NOW()),
('Realistic Calvin and Hobbes', 'Realistic version of Calvin and Hobbes characters', 'a realistic version of calvin and hobbes', 1, 17, 1, 0, 0, 1, '{"original_id": "12f53fd6-7f81-48a3-a8ee-22fd0481b4d0", "characters": "Calvin and Hobbes", "style": "realistic"}', NOW(), NOW()),
('Cat Selfie at Big Ben', 'Realistic cat taking selfie in front of Big Ben with raincoat', 'A realistic gray cat taking a selfie in front of Big Ben in London, raindrops on its fur, wearing a miniature raincoat', 1, 7, 1, 0, 0, 1, '{"original_id": "8a3ddf26-4a72-4501-94d4-8e707d4fb857", "animal": "cat", "location": "Big Ben", "style": "selfie"}', NOW(), NOW()),
('Minions NYC Paparazzi Photo', 'TMZ paparazzi photo of Minions getting late night snack in NYC', 'TMZ papparazzi photo of 3 minions, flash photo, at night, gritty nyc streets, getting a late night snack', 1, 6, 1, 0, 0, 1, '{"original_id": "3ec93c9a-ebf4-45e2-9afb-1857f9c0f864", "characters": "Minions", "style": "paparazzi", "location": "NYC"}', NOW(), NOW()),
('Kirby Club Exit Paparazzi', 'Cute Kirby leaving club at night with paparazzi attention', 'cute Kirby leaving the club at night, wearing black sunglasses, pappaeazzi flash photo, does not want to be photographed.. motion blur, blurry, grainy. TMZ logo in corner. crowds in the background, flashes from camera going off.', 1, 6, 1, 0, 0, 1, '{"original_id": "d498bab9-72d3-4c85-a858-e0728a092de7", "character": "Kirby", "situation": "nightlife", "style": "paparazzi"}', NOW(), NOW()),
('MarioKart Cinematic Poster', 'Cinematic movie poster design for MarioKart', 'cinematic mariokart movie poster', 1, 14, 3, 0, 0, 1, '{"original_id": "be365f05-8158-40bc-8de4-20a388cc49d7", "game": "MarioKart", "style": "cinematic", "purpose": "poster"}', NOW(), NOW()),
('Darth Vader Wedding Photography', 'Wedding photography of Darth Vader walking daughter down aisle', 'Wedding photography of Darth Vader walking his daughter down the aisle, still breathing heavily through his mask but dabbing a tear with a white handkerchief', 1, 6, 1, 0, 0, 1, '{"original_id": "21b5cd73-74d8-44fb-9111-a8756818a805", "character": "Darth Vader", "situation": "wedding", "mood": "emotional"}', NOW(), NOW()),
('Nightvision Chimp Trailcam', 'Trailcam footage of chimps captured with nightvision', 'trailcam footage, chimps, nightvision', 1, 18, 2, 0, 0, 1, '{"original_id": "1ed7aad5-131e-4843-9037-59011703875c", "animals": "chimps", "equipment": "trailcam", "lighting": "nightvision"}', NOW(), NOW()),
('Musk Trump Gaming Session', 'Unremarkable iPhone selfie of Elon Musk and Trump gaming', 'An extremely unremarkable, blurry iPhone selfie photo with no proper framing or focus — a badly timed, accidental-looking snapshot.\nThe photo has mild motion blur and harsh, uneven lighting from a flickering ceiling lamp.\nThe camera angle is awkward and tilted, like the phone was slipping from someone''s hand mid-shot.\nIn the scene\nElon Musk sits slouched on a worn-out couch covered in random blankets, wearing an oversized T-shirt with a ketchup stain, playing a dusty old Xbox 360 controller with intense focus.\nNext to him, trump is half-asleep, wrapped in a giant burrito blanket, drooling slightly onto a TV remote.\nThe room is cluttered with empty pizza boxes, laundry piles, and a few knocked-over cans of Monster Energy drink.\nThe overall mood is extremely mundane, chaotic, and mildly depressing in an oddly humorous way.', 1, 3, 1, 0, 0, 1, '{"original_id": "5dac4f26-75a7-4276-8b75-32a38ed3f8dd", "people": ["Elon Musk", "Trump"], "situation": "gaming", "style": "casual"}', NOW(), NOW()),
('Jacked Anime Girl CrossFit', 'Anime girl with muscular physique competing in CrossFit', 'a jacked anime girl competing in a CrossFit competition', 1, 4, 1, 0, 0, 1, '{"original_id": "71a47023-e031-4e75-9026-5a12fa94c81d", "style": "anime", "sport": "CrossFit", "body": "muscular"}', NOW(), NOW()),
('Kiki Delivery Service Portrait', 'High-resolution realistic portrait of Kiki from Delivery Service', 'The high-resolution realistic portrait of Kiki in "The Witch Home Delivery Service" depicts a young Japanese beauty cosplayer, with delicate facial features, flowing skin, delicate facial texture, and light and natural makeup, she is relaxed riding a broomstick through the sunny sky wearing a red bow on her head, wearing a black dress and carrying a brown leather satchel on her back, flying on a broomstick with the black cat Gigi, their figures soar over the sparkling coastal water, dynamic wind effects', 1, 2, 1, 0, 0, 1, '{"original_id": "e7d6e85d-0ce0-49b1-b8a1-813e912fd90d", "character": "Kiki", "movie": "Kiki''s Delivery Service", "style": "realistic"}', NOW(), NOW()),
('Alien Neon Heart Art', 'Photorealistic alien made of obsidian holding neon heart in glass cube', 'an alien made of obsidian and slimy darkness with glowing white eyes stands inside a thin translucent giant glass cube in the middle of a red neon void. inside the cube he holds a melting small organic human heart made of neon white liquid. photorealistic', 1, 12, 1, 0, 0, 1, '{"original_id": "1dbfc2d4-f56a-4097-9c32-2a1c9f91e2dd", "subject": "alien", "style": "photorealistic", "elements": ["obsidian", "neon", "glass"]}', NOW(), NOW()),
('Cookie Monster Presidential Portrait', 'Presidential portrait of Cookie Monster in Oval Office', 'Presidential Portrait photo of Cookie Monster in the Oval Office. He is holding up a signed piece of paper which reads "NO TARIFFS ON COOKIES FROM CHINA" in a LARGE text. Is is the central part of the frame. In his other hand he is holding a cookie.', 1, 6, 1, 0, 0, 1, '{"original_id": "b1f1d087-823f-4ebb-a691-daf567b2f7d6", "character": "Cookie Monster", "setting": "Oval Office", "theme": "political"}', NOW(), NOW()),
('90s Anime Scratchy Style', 'Vintage 90s anime with scratchy pen strokes and angular shapes', 'Vintage 90s anime, Scratchy pen strokes, blind contour, perspective closeup, beautiful girl, face in darkness, stark hatch shaded sketchy scribbly, ink, strong angular shapes, woodcut shading, pen strokes, pouty lips, hungry eyes, minimalist realistic, proportions', 1, 4, 1, 0, 0, 1, '{"original_id": "19eff5e4-34da-46bb-98c5-94f9949a8c40", "era": "90s", "style": "sketchy", "technique": "pen strokes"}', NOW(), NOW()),
('Capybara Ocean Swimming', 'Cute capybara swimming in ocean with Portra 400 film style', 'a cute capybara swimming in the ocean, portra 400, wide angle shot, majestic fog', 1, 13, 1, 0, 0, 1, '{"original_id": "73c54bb1-756b-437e-8337-e55c8b6c28ed", "animal": "capybara", "film": "Portra 400", "environment": "ocean"}', NOW(), NOW()),
('Trump Evil Anime Style', 'Donald Trump portrayed in evil anime style', 'trump in evil anime style', 1, 4, 1, 0, 0, 1, '{"original_id": "b0422224-fe8d-492a-81f7-06f117ae5e02", "person": "Trump", "style": "anime", "mood": "evil"}', NOW(), NOW()),
('Phonk Song Poster Design', 'Phonk song poster with grungy analog photo style', 'Phonk song poster of a Grungy analog photo, late 90s/early 2000s style,  Ring camera footage EPIC Games character a soldier In stealth mode, night time, black ops cinema influence, HDR10+', 1, 10, 6, 0, 0, 1, '{"original_id": "bbb0affb-b370-4c0d-912c-f614f34cf4bc", "music": "Phonk", "style": "grungy", "era": "90s-2000s"}', NOW(), NOW());